HousekeepFilesInfo.sysName=System name
HousekeepFilesTask.taskId=Task ID
HousekeepFilesTask.taskName=Task name
HousekeepFilesTask.taskPtn=Task pattern
HousekeepFilesTask.remoteServer=Remote server
HousekeepFilesTask.srcPath=Source path
HousekeepFilesTask.isSrcPathDir=Source path is directory
HousekeepFilesTask.unit=Target unit
HousekeepFilesTask.value=Target value
HousekeepFilesTask.actionForNoSrcPath=Action when source file not found
HousekeepFilesTask.destPath=Destination path
HousekeepFilesTask.isDestPathDir=Destination path is directory
HousekeepFilesTask.doesOverwriteDestPath=Overwrite destination file
HousekeepFilesTask.actionForToFileExists=Action when destination file exists
HousekeepFilesPath.key=Key
HousekeepFilesPath.value=Value (path)
HousekeepFilesAuth.remoteServer=Server name
HousekeepFilesAuth.protocol=Protocol
HousekeepFilesAuth.port=Port number
HousekeepFilesAuth.authType=Authentication type
HousekeepFilesAuth.userName=Username
HousekeepFilesAuth.password=Password
HousekeepFilesAuth.keyPath=Key path
