HousekeepInfoBean.isSoftDelete=Soft delete flag column name
HousekeepInfoBean.softDeleteUpdateTimestampColumn=Soft delete: update timestamp column name
HousekeepInfoBean.softDeleteUpdateUserIdColumn=Soft delete: update user ID column name
HousekeepInfoBean.softDeleteUpdateUserIdColumnValue=Soft delete: update user ID column value
HousekeepInfoBean.softDeleteUpdateUserIdColumnNeedsQuotationMark=Soft delete: update user ID column literal symbol
