## HousekeepInfoBean
housekeepInfoBean.taskId=Task ID
housekeepInfoBean.dbConnectionInfoId=DB Connection ID
housekeepInfoBean.isSoftDelete=Soft / Hard Delete
housekeepInfoBean.isSoftDeleteInternalValue=Soft / Hard Delete (internal value)
housekeepInfoBean.table=Table Name
housekeepInfoBean.idColumn=ID Column Name
housekeepInfoBean.idColumnNeedsQuotationMark=ID Column Literal Symbol
housekeepInfoBean.timestampColumn=Expiration Check: Timestamp Column Name
housekeepInfoBean.timestampColumnKind=Expiration Check: Timestamp Column Data Type
housekeepInfoBean.deleteTargetInDays=Expiration Check: Validity Days
housekeepInfoBean.softDeleteColumn=Soft Delete Column Name
housekeepInfoBean.softDeleteUpdateTimestampColumn=Soft Delete: Update Timestamp Column Name
housekeepInfoBean.softDeleteUpdateUserIdColumn=Soft Delete: Update User ID Column Name
housekeepInfoBean.softDeleteUpdateUserIdColumnNeedsQuotationMark=Soft Delete: Update User ID Column Literal Symbol
housekeepInfoBean.softDeleteUpdateUserIdColumnValue=Soft Delete: Update User ID Column Value

## DbConnectionInfoBean
dbConnectionInfoBean.id=DB Connection ID
dbConnectionInfoBean.driverName=Driver Name
dbConnectionInfoBean.protocol=Connection URL: Protocol
dbConnectionInfoBean.server=Connection URL: Server
dbConnectionInfoBean.port=Connection URL: Port
dbConnectionInfoBean.database=Connection URL: Database
dbConnectionInfoBean.username=Username
dbConnectionInfoBean.password=Password

## RelatedTableInfoBean
relatedTableInfoBean.taskId=Task ID
relatedTableInfoBean.isSoftDeleteInternalValue=Soft / Hard Delete (internal value)
relatedTableInfoBean.relatedTableProcessPattern=Related Table Process Pattern
relatedTableInfoBean.relatedTableProcessPatternInternalValue=Related Table Process Pattern (internal value)
relatedTableInfoBean.targetTableColumn=Target Table Column Name
relatedTableInfoBean.relatedTable=Related Table Name
relatedTableInfoBean.relatedTableIdColumn=Related Table ID Column Name
relatedTableInfoBean.relatedTableIdColumnNeedsQuotationMark=Related Table ID Column Literal Symbol
relatedTableInfoBean.softDeleteColumn=Soft Delete Column Name
relatedTableInfoBean.softDeleteUpdateTimestampColumn=Soft Delete: Update Timestamp Column Name
relatedTableInfoBean.softDeleteUpdateUserIdColumn=Soft Delete: Update User ID Column Name
relatedTableInfoBean.softDeleteUpdateUserIdColumnNeedsQuotationMark=Soft Delete: Update User ID Column Literal Symbol
relatedTableInfoBean.softDeleteUpdateUserIdColumnValue=Soft Delete: Update User ID Column Value

## WhereConditionInfoBean
whereConditionInfoBean.taskId=Task ID
whereConditionInfoBean.conditionColumn=Search Condition Column Name
whereConditionInfoBean.conditionColumnNeedsQuotationMark=Search Condtion Column Literal Symbol
whereConditionInfoBean.conditionColumnValue=Search Condition Column Value
